# Generated by Django 6.1.1 on 2026-09-14 14:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("invoices", "0002_invoice_billing_address_invoice_billing_city_and_more"),
        ("products", "0004_remove_paint_products_pa_brand_i_7b4a8b_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="delivery_challan_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="delivery_challan_number",
        ),
        migrations.CreateModel(
            name="DeliveryChallan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_number", models.CharField(max_length=50, unique=True)),
                (
                    "challan_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("po_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "shipping_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "shipping_pin_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "shipping_gst_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "eway_bill_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("removal_date", models.DateField(blank=True, null=True)),
                ("removal_time", models.TimeField(blank=True, null=True)),
                (
                    "dispatched_through",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("lr_number", models.CharField(blank=True, max_length=50, null=True)),
                ("lr_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_challans",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "db_table": "invoices_delivery_challan",
            },
        ),
        migrations.CreateModel(
            name="DeliveryChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "hsn_sac_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "pack_description",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.deliverychallan",
                    ),
                ),
                (
                    "paint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="delivery_challan_items",
                        to="products.paint",
                    ),
                ),
            ],
            options={
                "db_table": "invoices_delivery_challan_item",
            },
        ),
        migrations.AddIndex(
            model_name="deliverychallan",
            index=models.Index(
                fields=["challan_date"], name="invoices_de_challan_48f596_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverychallan",
            index=models.Index(
                fields=["client", "challan_date"], name="invoices_de_client__2f92cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverychallanitem",
            index=models.Index(
                fields=["delivery_challan"], name="invoices_de_deliver_54f255_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverychallanitem",
            index=models.Index(fields=["paint"], name="invoices_de_paint_i_10caaf_idx"),
        ),
    ]
