# Generated by Django 6.1.1 on 2026-09-14 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("invoices", "0003_remove_invoice_delivery_challan_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverychallan",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_delivery_challans",
                to="accounts.admin",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="delivery_challans",
            field=models.ManyToManyField(
                blank=True, related_name="invoices", to="invoices.deliverychallan"
            ),
        ),
    ]
