# Generated by Django 6.1.1 on 2026-09-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("invoices", "0004_deliverychallan_created_by_invoice_delivery_challans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverychallan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_delivery_challans",
                to="accounts.admin",
            ),
        ),
    ]
