# Generated by Django 5.0.7 on 2026-09-10 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must contain exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pin_code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "gst_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "clients_client",
                "indexes": [
                    models.Index(
                        fields=["phone_number"], name="clients_cli_phone_n_6adefc_idx"
                    ),
                    models.Index(
                        fields=["gst_number"], name="clients_cli_gst_num_58ca2b_idx"
                    ),
                    models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
                ],
            },
        ),
    ]
