# Generated by Django 5.0.7 on 2026-09-10 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "products_brand",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "products_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Paint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=150)),
                (
                    "finish",
                    models.CharField(
                        choices=[
                            ("MATTE", "Matte"),
                            ("GLOSSY", "Glossy"),
                            ("SATIN", "Satin"),
                            ("EGGSHELL", "Eggshell"),
                            ("SEMI_GLOSS", "Semi Gloss"),
                        ],
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(max_length=50)),
                ("shade_code", models.CharField(max_length=20)),
                (
                    "size",
                    models.CharField(help_text="Example: 1L, 4L, 20L", max_length=20),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gst_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paints",
                        to="products.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paints",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "products_paint",
                "indexes": [
                    models.Index(
                        fields=["brand", "category"],
                        name="products_pa_brand_i_7b4a8b_idx",
                    ),
                    models.Index(
                        fields=["shade_code"], name="products_pa_shade_c_c34cf3_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="paint",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="paint_price_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="paint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gst_percentage__gte", 0), ("gst_percentage__lte", 100)
                ),
                name="paint_gst_percentage_0_100",
            ),
        ),
    ]
