# Generated by Django 6.1.1 on 2026-09-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_paintimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="paint",
            name="hsn_sac_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
