# Generated by Django 6.1.1 on 2026-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_paint_hsn_sac_code"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="paint",
            name="products_pa_brand_i_7b4a8b_idx",
        ),
        migrations.AddIndex(
            model_name="paint",
            index=models.Index(
                fields=["category"], name="products_pa_categor_2ae539_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="paint",
            name="brand",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
